@hostname = localhost
@port = 3001
@host = {{hostname}}:{{port}}
@contentType = application/json

###

# @name sessions
POST http://{{host}}/sessions HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "bortolettohenrique@gmail.com",
  "password": "Mohave796523#"
}

###
@token = Bearer {{sessions.response.body.token}}

###

# @name tags
GET http://{{host}}/tags HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{token}}

###

# @name notes
GET http://{{host}}/notes?title=&tags= HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{token}}